# Generated by Django 5.2 on 2026-05-28 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='perfumes',
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='perfume',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='perfumes.carrito'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='perfumes.perfume'),
        ),
    ]
